# Generated by Django 4.2.3 on 2023-07-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(default='images/avatar.webp', upload_to='images/'),
        ),
    ]
