# Generated by Django 4.2.3 on 2023-07-09 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court', models.CharField(choices=[('Court 1', 'Court 1'), ('Court 2', 'Court 2'), ('Court 3', 'Court 3'), ('Court 4', 'Court 4'), ('Court 5', 'Court 5')], max_length=50)),
                ('date', models.DateField()),
                ('first_party', models.TextField()),
                ('appointed_by', models.TextField()),
                ('law_and_section', models.TextField()),
                ('case_no', models.PositiveIntegerField()),
                ('police_station', models.CharField(max_length=50)),
                ('fixed_for', models.TextField(blank=True, null=True)),
                ('second_party', models.TextField(blank=True, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('case_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.casetype')),
            ],
        ),
    ]
