# Generated by Django 4.2.3 on 2023-07-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(choices=[('Option 1', 'Option 1'), ('Option 2', 'Option 2'), ('Option 3', 'Option 3'), ('Option 4', 'Option 4'), ('Option 5', 'Option 5')], max_length=50)),
                ('court', models.CharField(choices=[('Court 1', 'Court 1'), ('Court 2', 'Court 2'), ('Court 3', 'Court 3'), ('Court 4', 'Court 4'), ('Court 5', 'Court 5')], max_length=50)),
                ('date', models.DateField()),
                ('first_party', models.TextField()),
                ('appointed_by', models.TextField()),
                ('law_and_section', models.TextField()),
                ('case_no', models.PositiveIntegerField()),
                ('police_station', models.CharField(max_length=50)),
                ('fixed_for', models.TextField()),
                ('second_party', models.TextField()),
                ('mobile_no', models.CharField(max_length=15)),
                ('comments', models.TextField()),
            ],
        ),
    ]
