# Generated by Django 4.2.3 on 2023-07-22 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='Representativ',
            new_name='Representative',
        ),
    ]
