# Generated by Django 4.2.3 on 2023-07-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('Running', 'Running'), ('Decided', 'Decided'), ('Abandoned', 'Abandoned')], default='Running', max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
