# Generated by Django 4.2.3 on 2023-07-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotations',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
